//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 2/6/2014 12:09:26 PM
namespace ConsoleFindItems
{
    
    /// <summary>
    /// There are no comments for HashForCashEntities in the schema.
    /// </summary>
    public partial class HashForCashEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new HashForCashEntities object using the connection string found in the 'HashForCashEntities' section of the application configuration file.
        /// </summary>
        public HashForCashEntities() : 
                base("name=HashForCashEntities", "HashForCashEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HashForCashEntities object.
        /// </summary>
        public HashForCashEntities(string connectionString) : 
                base(connectionString, "HashForCashEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HashForCashEntities object.
        /// </summary>
        public HashForCashEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "HashForCashEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
    }
}
